services:
  bike_polo_database:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - bike_polo_backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  bike_polo_app:
    build:
      context: .
      args:
        BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
    ports:
      - "3004:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@bike_polo_database:5432/${DB_NAME}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
    depends_on:
      bike_polo_database:
        condition: service_healthy
    networks:
      - bike_polo_backend

volumes:
  postgres_data:

networks:
  bike_polo_backend:
    driver: bridge
